### ISSUE TITLE
Convert to more specific return types in DICOMwebClient

### ISSUE THREAD

**Issue by ntenenz** [MGHComputationalPathology/dicomweb-client#20]
While it's common practice to accept `Sequence[T]` when a function can accept a list, tuple, etc., it's often best to be more specific with return types allowing those invoking the methods to have greater clarity of the type returned. In many of `DICOMwebClient`'s methods, current type hints provide a return value of `Sequence[T]` where `List[T]` would be more specific. I propose updating these types to the more specific values provided the API is comfortable committing to these types (which seems like a fairly innocuous commitment).

**Comment by hackermd** [comment]
Good point. ``List[T`` is also what the corresponding docstrings say.

**Comment by hackermd** [comment]
Merged into master branch. Will be included in next release.
