### ISSUE TITLE
Set headers request

### ISSUE THREAD

**Issue by phelys** [MGHComputationalPathology/dicomweb-client#22]
Hi, I need to know, how I can set headers request in every dicomweb requests. Nowadays, I have this issue to solve: has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ntenenz** [comment]
When creating the DICOMwebClient instance, there's an argument `headers` which allows for arbitrary headers to be set in every request. [Link](https://github.com/MGHComputationalPathology/dicomweb-client/blob/master/src/dicomweb_client/api.py#L216)

**Comment by phelys** [comment]
> When creating the DICOMwebClient instance, there's an argument `headers` which allows for arbitrary headers to be set in every request. [Link](https://github.com/MGHComputationalPathology/dicomweb-client/blob/master/src/dicomweb_client/api.py#L216)

**Comment by phelys** [comment]
> When creating the DICOMwebClient instance, there's an argument `headers` which allows for arbitrary headers to be set in every request. [Link](https://github.com/MGHComputationalPathology/dicomweb-client/blob/master/src/dicomweb_client/api.py#L216)

thanks, I will try it.
