### ISSUE TITLE
Expose basic authentication to CLI

### ISSUE THREAD

**Issue by ChillarAnand** [MGHComputationalPathology/dicomweb-client#35]
Currently, Dicom WebClient API has interface for an [authentication mechanism](https://dicomweb-client.readthedocs.io/en/latest/usage.html#authentication-and-authorization). However, when CLI this option is not exposed which limits the usage of CLI.

**Comment by hackermd** [comment]
@ChillarAnand username and password can be passed via the [--user](https://github.com/MGHComputationalPathology/dicomweb-client/blob/2304f1626d673c316f42bad61ad398806b20ac89/src/dicomweb_client/cli.py#L47-L50) and [--password](https://github.com/MGHComputationalPathology/dicomweb-client/blob/2304f1626d673c316f42bad61ad398806b20ac89/src/dicomweb_client/cli.py#L51-L54) CLI options. If a *username* but no *password* is provided, the user will be [prompted for a password](https://github.com/MGHComputationalPathology/dicomweb-client/blob/2304f1626d673c316f42bad61ad398806b20ac89/src/dicomweb_client/cli.py#L646) via the CLI. See also documentation of the [CLI of the dicomweb_client program](https://dicomweb-client.readthedocs.io/en/latest/package.html#dicomweb-client)

**Comment by ChillarAnand** [comment]
I was looking for user/password option. 

When I ran `--help`, these options weren't showing up. So, I thought they are not there. 

```
$ dicomweb_client --url http://localhost:8042/dicom-web search studies --help 
usage: dicomweb_client search studies [-h] [--filter KEY=VALUE] [--field NAME]
                                      [--limit NUM] [--offset NUM] [--fuzzy]
                                      [--prettify | --dicomize]

Search for DICOM studies.

optional arguments:
  -h, --help          show this help message and exit
  --filter KEY=VALUE  query filter criterion
  --field NAME        field that should be included in response
  --limit NUM         number of items that should be maximally retrieved
  --offset NUM        number of items that should be skipped
  --fuzzy             perform fuzzy matching
  --prettify          pretty print JSON response message
  --dicomize          convert JSON response message to DICOM data set
```

Thanks, @hackermd
