### ISSUE TITLE
Minimum python requirement question

### ISSUE THREAD

**Issue by jamesobutler** [MGHComputationalPathology/dicomweb-client#38]
What is the minimum python requirement when using version 0.50.0?  I see it specifies python 3.6 in the classifiers section, but then `python_requires` specifies python >3.6.

https://github.com/MGHComputationalPathology/dicomweb-client/blob/eb24ea2e8bd56584606eea718f02acd00f3f9962/setup.py#L31-L34

https://github.com/MGHComputationalPathology/dicomweb-client/blob/eb24ea2e8bd56584606eea718f02acd00f3f9962/setup.py#L49

**Comment by hackermd** [comment]
@jamesobutler Thanks for catching this. It's supposed to be `python_requires>=3.6`. I have fixed it with f1167c893d82cbfa9d3cd7a7ffc1272386b6cb85.

**Comment by jamesobutler** [comment]
I see that you've bumped your package release to 0.50.2 with this fix.  Do you plan on updating the package release on pypi as well? https://pypi.org/project/dicomweb-client/

**Comment by hackermd** [comment]
Yes :) Here you go: https://pypi.org/project/dicomweb-client/0.50.2/

**Comment by jamesobutler** [comment]
Great! Thanks!
