### ISSUE TITLE
Missing image data when using `retrieve_*` or `iter_*`

### ISSUE THREAD

**Issue by razorx89** [MGHComputationalPathology/dicomweb-client#39]
I switched from my own `aiohttp` based DicomWeb implementation to `dicomwebclient` for downloading image studies/series and observe quite often missing data in a single slice per image series (when using `retrieve_series` or `iter_series`). It can be reproduced for the very same image series and when retrieving more than one series in a row there is also some kind of buffer leakage introduced. The missing image data is replaced with data from probably a different series.

![image](https://user-images.githubusercontent.com/15977832/97713897-b8b75e00-1ac0-11eb-8568-815cdc73a3f0.png)

Two different download mechanisms, one based on `aiohttp` and the other on Scala and dcm4che, are able to retrieve the image data without any problems so I think it is actually a problem in the multi-part response parsing in this package.

**Comment by hackermd** [comment]
Thanks for reporting this @razorx89. Is there a publicly available data set that we could use to debug the problem?

**Comment by hackermd** [comment]
Thanks for immediately fixing this @razorx89!

**Comment by hackermd** [comment]
Included in release 0.50.3 (https://pypi.org/project/dicomweb-client/0.50.3)
