### ISSUE TITLE
Query regarding the body of STOW-RS request

### ISSUE THREAD

**Issue by lafith** [MGHComputationalPathology/dicomweb-client#54]
I was trying to parse the byte array send by store request using this client and I am getting an EOF error of reading. I checked the content from the request body and reading the test dicom file directly and found some difference at the beginning.
- content from http post request
![http_body](https://user-images.githubusercontent.com/39316548/134767050-b221ab5d-2168-4ada-95f8-f5bf136acdfc.png)
- content from reading file directly
![from_file](https://user-images.githubusercontent.com/39316548/134767058-2ef4e5ec-c04d-43b5-9099-ec8dc8803c17.png)
What is this difference at the begnning? I am trying to pass the POST request body directly to a parsing function like [this](https://pkg.go.dev/github.com/suyashkumar/dicom#Parse)

**Comment by hackermd** [comment]
The request message has [multipart](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) content type. Therefore, the message body contains one or more DICOM data sets and encapsulation boundaries.

**Comment by hackermd** [comment]
See DICOM [PS 3.18 Section 8.6](http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_8.6.html#sect_8.6.1.2)
