### ISSUE TITLE
Retrive metadata is QIDO-RS or WADO-RS?

### ISSUE THREAD

**Issue by TakasiSHIH** [MGHComputationalPathology/dicomweb-client#55]
Many server support to retrieve metadata by QIDO.
But parameter of dicomweb-client retrieve metadata api is _Transaction.RETRIEVE.
It cause api to get wrong prefix of URI.

Does  it should be changed the parameter to _Transaction.SEARCH?

**Comment by hackermd** [comment]
Retrieval of metadata is part of the Retrieve Transaction (i.e., WADO-RS). See [Part 3 Section 10.4.1.1.2 Metadata Resources](http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_10.4.html#sect_10.4.1.1.2)

**Comment by TakasiSHIH** [comment]
hackermd , thank you very much!!!
