### ISSUE TITLE
Orthanc Support

### ISSUE THREAD

**Issue by liamcarter111** [MGHComputationalPathology/dicomweb-client#61]
There seem to be issues when integrating with Orthanc. Orthanc uses SHA-1 hashes of Instance UIDs. This fails DICOM UID verification giving "DICOM UID has invalid format.". It is clearly obvious this is not a valid DICOM UID but support for Orthanc is mentioned.

![Screenshot from 2022-01-24 20-32-25](https://user-images.githubusercontent.com/7712589/150860111-16d3f637-4cea-4748-99e9-cc72cda66a48.png)
 

See
https://book.orthanc-server.com/faq/orthanc-ids.html

**Comment by hackermd** [comment]
Thanks for reporting this issue @liamcarter111. Are you sure are querying against the DICOMweb interface of Orthanc?

**Comment by hackermd** [comment]
In general, we try to avoid providing hacks around standard compliance issues. If the Orthanc DICOMweb server returns search results that contain invalid DICOM UIDs, I would consider that a bug in Orthanc.

**Comment by liamcarter111** [comment]
You are right missing `/dicom-web`. Confused me as it partially worked. Thanks @hackermd
